<?xml version="1.0" encoding="utf-8"?><Database Name="ConnectToCar" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=GREGWIN8\SQLEXPRESS;Initial Catalog=ConnectToCar;User ID=dev" SettingsObjectName="ConnectToCar.Properties.Settings" SettingsPropertyName="ConnectToCarConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VehicleLocation" Member="VehicleLocations">
    <Type Name="VehicleLocation">
      <Column Name="locationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="vehicleGUID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dateTimeStamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="lat" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="lng" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>